site_title: Kent Maps
banner_image: https://kg.jstor.org/w/images/c/cc/Viking_Bay,_Broadstairs.jpg
base_url: 'https://kg.jstor.org'
markup: 'wikitext'
index: Kent:Essays
about: Kent:About
help: https://jstor-labs.github.io/visual-essays/help.md
contact: Kent:Contact
gh_path: https://kent-map.github.io
app_version: 0.2.8
visual_essays_version: 0.3.11
context: kent-maps